# Generated by Django 3.0.5 on 2020-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='content',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='updated',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='photo',
            name='id_Deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
