# Generated by Django 3.0.5 on 2020-04-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200426_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='id_Deleted',
            new_name='is_Deleted',
        ),
    ]
