# Generated by Django 3.0.5 on 2020-04-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200426_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='timestamp',
            new_name='publish_time',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_Deleted',
        ),
    ]
